package:
   name: metagraph-stellargraph
   version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
   path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}
  string: {{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    - stellargraph
    - metagraph >=0.2.5

test:
  requires:
    - metagraph-dev
  commands:
    - py.test --cov-report term-missing --cov=metagraph_stellargraph --pyargs metagraph.tests

about:
  home: https://github.com/metagraph-dev/metagraph-stellargraph
  license: Apache2
  license_file: LICENSE
  summary: Metagraph plugin for stellargraph
